# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Build Apple Color Emoji font
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Set up Python
        uses: actions/setup-python@v5 # https://github.com/actions/setup-python
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install fonttools
          python -m pip install notofonttools
          sudo apt update
          sudo apt install --yes optipng zopfli pngquant imagemagick
      - name: Build Apple color emoji font
        run: |
          make -j
          make install
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
        with:
          name: apple-color-emoji-font
          path: AppleColorEmoji.ttf
      - name: Archive build artifacts for Windows
        uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
        with:
          name: AppleColorEmoji_WindowsCompatible
          path: AppleColorEmoji_WindowsCompatible.ttf

